# Generated by Django 3.0.8 on 2021-01-01 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nameofparam', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='interviewer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=20)),
                ('isadmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
        migrations.CreateModel(
            name='pt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_type', models.CharField(max_length=15)),
                ('e_score', models.IntegerField()),
                ('n_score', models.IntegerField()),
                ('f_score', models.IntegerField()),
                ('j_score', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
        migrations.CreateModel(
            name='pi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.IntegerField()),
                ('param2', models.IntegerField()),
                ('param3', models.IntegerField()),
                ('param4', models.IntegerField()),
                ('param5', models.IntegerField()),
                ('param6', models.IntegerField()),
                ('param7', models.IntegerField()),
                ('param8', models.IntegerField()),
                ('feedback', models.TextField()),
                ('interviewer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer3', to='calc.interviewer')),
                ('interviewer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer4', to='calc.interviewer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
        migrations.CreateModel(
            name='gd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.IntegerField()),
                ('param2', models.IntegerField()),
                ('param3', models.IntegerField()),
                ('param4', models.IntegerField()),
                ('param5', models.IntegerField()),
                ('feedback', models.TextField()),
                ('interviewer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer1', to='calc.interviewer')),
                ('interviewer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer2', to='calc.interviewer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
        migrations.CreateModel(
            name='essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user')),
            ],
        ),
    ]
