# Generated by Django 3.0.8 on 2021-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pyt',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('personality', models.CharField(max_length=10)),
                ('e_score', models.IntegerField()),
                ('n_score', models.IntegerField()),
                ('f_score', models.IntegerField()),
                ('j_score', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
