# Generated by Django 3.0.8 on 2021-01-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_pyt'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('cat_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_n',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=20)),
                ('spl_b', models.IntegerField()),
                ('isadmin', models.BooleanField()),
            ],
        ),
    ]
