# Generated by Django 3.0.8 on 2021-01-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210106_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cat',
        ),
    ]
