# Generated by Django 3.0.8 on 2021-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_delete_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='cats',
            fields=[
                ('category', models.CharField(max_length=50)),
                ('cat_type', models.CharField(max_length=50)),
                ('q_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
