# Generated by Django 3.0.8 on 2021-01-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20210106_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_id', models.IntegerField()),
                ('q_no', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user_n')),
            ],
        ),
        migrations.CreateModel(
            name='aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('timespent', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user_n')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('par_cat', models.CharField(max_length=50)),
                ('q_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.answers')),
            ],
        ),
        migrations.DeleteModel(
            name='apti',
        ),
        migrations.DeleteModel(
            name='cats',
        ),
    ]
