# Generated by Django 3.0.8 on 2021-01-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20210107_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_id', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user_n')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.IntegerField()),
                ('cat_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='q_no',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='cat_tag',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.AddField(
            model_name='answers',
            name='q_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.question'),
        ),
    ]
