# Generated by Django 3.0.8 on 2021-01-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20210107_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='gd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_id', models.IntegerField()),
                ('topic', models.CharField(max_length=40)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user_n')),
            ],
        ),
    ]
