# Generated by Django 3.0.8 on 2021-01-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20210110_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='gds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_id', models.IntegerField()),
                ('topic', models.CharField(max_length=40)),
                ('analysis', models.IntegerField()),
                ('body_l', models.IntegerField()),
                ('team_s', models.IntegerField()),
                ('articulation', models.IntegerField()),
                ('participation', models.IntegerField()),
                ('total', models.IntegerField()),
                ('feedback', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.user_n')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.interviewer')),
            ],
        ),
        migrations.DeleteModel(
            name='gd',
        ),
    ]
